name: Model CICD
on: workflow_dispatch
job:
  model-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-Python
        with:
          python-version: 3.12
      - name: Install python dependencies
        runs: |
          python pip install --upgrade pip
          python pip install -r requirements.txt
      - name: Split Dataset
        runs: python src/0-split-dataset.py 